// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "@popperjs/core"
import "bootstrap"
import "chatbot"
import "controllers/search_dropdown"
import "controllers/personal_info"
import "controllers/password_toggle"
import "controllers/sort_events"
